import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowDownRight, ArrowUpRight, Banknote, Building2, Calculator, Car, ChevronRight, Coins, Home, Landmark, LineChart, Map, Menu, Search, ShoppingBag, Sparkles, Target, TrendingUp, Trophy, Wallet, X, Zap} from 'lucide-react';
import './styles.css';

const seedAssets = [
  {id:'aapl', name:'Apple Inc.', ticker:'AAPL', type:'Stock', price:229.31, change:1.24, icon:''},
  {id:'msft', name:'Microsoft', ticker:'MSFT', type:'Stock', price:506.69, change:0.88, icon:'M'},
  {id:'nvda', name:'NVIDIA', ticker:'NVDA', type:'Stock', price:179.30, change:2.71, icon:'N'},
  {id:'btc', name:'Bitcoin', ticker:'BTC', type:'Crypto', price:113420.00, change:-0.64, icon:'₿'},
  {id:'eth', name:'Ethereum', ticker:'ETH', type:'Crypto', price:4380.20, change:1.91, icon:'Ξ'},
  {id:'gold', name:'Gold', ticker:'XAU', type:'Commodity', price:3365.40, change:0.43, icon:'Au'},
  {id:'tesla', name:'Tesla', ticker:'TSLA', type:'Stock', price:335.58, change:-1.12, icon:'T'},
  {id:'coca', name:'Coca-Cola', ticker:'KO', type:'Stock', price:70.14, change:0.36, icon:'C'},
];

const properties = [
  {id:'land-ibadan', name:'Ibadan Growth Plot', location:'Ibadan, Oyo', price:250000, icon:<Map size={20}/>, yield:4.2},
  {id:'apt-lagos', name:'Lagos City Apartment', location:'Victoria Island, Lagos', price:18500000, icon:<Building2 size={20}/>, yield:7.8},
  {id:'villa-abuja', name:'Abuja Executive Villa', location:'Maitama, Abuja', price:42000000, icon:<Home size={20}/>, yield:8.4},
  {id:'shop-ibadan', name:'Commercial Shop', location:'Ring Road, Ibadan', price:7500000, icon:<ShoppingBag size={20}/>, yield:9.1},
];

const initial = {balance:0, totalEarned:0, energy:100, owned:[], portfolio:{}, transactions:[], tapLevel:1};
function loadState(){try{return {...initial,...JSON.parse(localStorage.getItem('avm-state')||'{}')}}catch{return initial}}
const money = n => '₦'+Number(n||0).toLocaleString('en-NG',{maximumFractionDigits:2});

function App(){
 const [state,setState]=useState(loadState); const [tab,setTab]=useState('home'); const [search,setSearch]=useState(''); const [showCalc,setShowCalc]=useState(false); const [toast,setToast]=useState(''); const [mobile,setMobile]=useState(false);
 const [assets,setAssets]=useState(seedAssets);
 useEffect(()=>localStorage.setItem('avm-state',JSON.stringify(state)),[state]);
 useEffect(()=>{const id=setInterval(()=>setAssets(a=>a.map(x=>({...x,price:Math.max(0.01,x.price*(1+(Math.random()-.49)*.004)),change:x.change+(Math.random()-.5)*.35}))),3500);return()=>clearInterval(id)},[]);
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),1800)};
 const tap=()=>{const earned=5*state.tapLevel; if(state.energy<1){notify('Rest and come back for more energy.');return} setState(s=>({...s,balance:s.balance+earned,totalEarned:s.totalEarned+earned,energy:s.energy-1,transactions:[{type:'Work',amount:earned,time:new Date().toLocaleTimeString(),note:'Tap-to-earn shift'},...s.transactions].slice(0,20)}));notify(`+${money(earned)} earned`)};
 const buy=(asset,qty)=>{const cost=asset.price*qty;if(state.balance<cost){notify('Not enough virtual cash. Keep working.');return}setState(s=>({...s,balance:s.balance-cost,portfolio:{...s.portfolio,[asset.id]:(s.portfolio[asset.id]||0)+qty},transactions:[{type:'Buy',amount:cost,time:new Date().toLocaleTimeString(),note:`${qty} ${asset.ticker}`},...s.transactions].slice(0,20)}));notify(`Bought ${qty} ${asset.ticker}`)};
 const filtered=assets.filter(a=>(a.name+a.ticker+a.type).toLowerCase().includes(search.toLowerCase()));
 const portfolioValue=Object.entries(state.portfolio).reduce((sum,[id,q])=>sum+(assets.find(a=>a.id===id)?.price||0)*q,0);
 const nav=[['home','Overview',Activity],['work','Work',Zap],['market','Markets',LineChart],['assets','My Assets',Wallet],['world','Virtual World',Map]];
 return <div className="app-shell">
   <aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><img src="/logo.svg"/><div><b>ABLECT</b><span>VIRTUAL MONEY</span></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div>
    <div className="nav-label">COMMAND CENTER</div>{nav.map(([id,label,I])=><button className={tab===id?'nav active':'nav'} onClick={()=>{setTab(id);setMobile(false)}} key={id}><I size={19}/><span>{label}</span></button>)}
    <div className="sidebar-bottom"><button className="nav" onClick={()=>setShowCalc(true)}><Calculator size={19}/><span>Calculator</span></button><div className="mini-status"><span>VIRTUAL ECONOMY</span><strong><i/> LIVE SIMULATION</strong></div></div>
   </aside>
   <main className="main"><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="search"><Search size={17}/><input placeholder="Search markets, properties..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="header-actions"><button className="icon-btn" onClick={()=>setShowCalc(true)}><Calculator size={18}/></button><div className="profile"><div className="avatar">A</div><div><b>Player</b><span>Level {state.tapLevel}</span></div></div></div></header>
    <div className="content">
      {tab==='home'&&<HomeView state={state} tap={tap} portfolioValue={portfolioValue} notify={notify} />}
      {tab==='work'&&<WorkView state={state} tap={tap} />}
      {tab==='market'&&<MarketView assets={filtered} buy={buy} balance={state.balance}/>} 
      {tab==='assets'&&<AssetsView state={state} assets={assets} portfolioValue={portfolioValue}/>} 
      {tab==='world'&&<WorldView state={state} properties={properties} notify={notify}/>} 
    </div>
   </main>
   {toast&&<div className="toast"><Sparkles size={16}/>{toast}</div>}
   {showCalc&&<CalculatorModal close={()=>setShowCalc(false)}/>} 
 </div>
}

function HomeView({state,tap,portfolioValue}){return <>
 <section className="hero"><div><span className="eyebrow"><i/> VIRTUAL ECONOMY ONLINE</span><h1>Build your fortune.<br/><em>Own your world.</em></h1><p>Start at ₦0. Work for every naira, trade real-world markets, then turn your virtual wealth into land, homes, cars and businesses.</p><button className="primary" onClick={tap}><Zap size={18}/> WORK FOR MONEY <ChevronRight size={18}/></button></div><div className="hero-orb"><div className="orb-ring r1"/><div className="orb-ring r2"/><div className="orb-core"><Coins size={42}/><span>₦0 →</span><b>YOUR EMPIRE</b></div></div></section>
 <div className="metrics"><Metric icon={<Banknote/>} label="Cash Balance" value={money(state.balance)}/><Metric icon={<TrendingUp/>} label="Portfolio" value={money(portfolioValue)}/><Metric icon={<Target/>} label="Total Earned" value={money(state.totalEarned)}/><Metric icon={<Zap/>} label="Energy" value={`${state.energy}/100`}/></div>
 <section className="grid2"><div className="panel work-card"><div className="panel-head"><div><span className="kicker">YOUR FIRST JOB</span><h2>Tap. Work. Earn.</h2></div><span className="pill">+₦5 / tap</span></div><div className="work-stage"><div className="tap-glow"/><button className="earn-button" onClick={tap}><Zap size={36}/><strong>WORK</strong><small>EARN ₦5</small></button><div className="work-copy"><b>Every fortune starts at zero.</b><span>Use energy to complete virtual shifts and build your first capital.</span></div></div></div><div className="panel"><div className="panel-head"><div><span className="kicker">MARKET PULSE</span><h2>Real-world assets</h2></div><button className="text-btn">Open market <ChevronRight size={15}/></button></div><div className="asset-list">{seedAssets.slice(0,4).map(a=><div className="asset-row" key={a.id}><div className="asset-icon">{a.icon}</div><div className="asset-name"><b>{a.name}</b><span>{a.ticker}</span></div><strong>{money(a.price)}</strong><span className={a.change>=0?'up':'down'}>{a.change>=0?'+':''}{a.change.toFixed(2)}%</span></div>)}</div></div></section>
 <section className="panel journey"><div className="panel-head"><div><span className="kicker">THE JOURNEY</span><h2>From worker to owner</h2></div></div><div className="steps"><Step n="01" icon={<Zap/>} title="Work" text="Earn your first capital."/><Step n="02" icon={<LineChart/>} title="Trade" text="Grow it through markets."/><Step n="03" icon={<Building2/>} title="Acquire" text="Buy virtual real-world assets."/><Step n="04" icon={<Trophy/>} title="Build" text="Create your virtual empire."/></div></section>
 </>}
function Metric({icon,label,value}){return <div className="metric"><div className="metric-icon">{icon}</div><div><span>{label}</span><b>{value}</b></div></div>}
function Step({n,icon,title,text}){return <div className="step"><span>{n}</span><div className="step-icon">{icon}</div><b>{title}</b><small>{text}</small></div>}
function WorkView({state,tap}){return <section><div className="page-title"><span className="eyebrow"><i/> CAREER MODE</span><h1>Work for your first million.</h1><p>You begin with exactly ₦0. No handouts. Your empire starts with effort.</p></div><div className="work-large panel"><div className="job-banner"><div className="job-icon"><Zap/></div><div><span>ENTRY JOB</span><h2>Virtual Freelancer</h2><p>Complete a shift and get paid from the simulation economy.</p></div><div className="pay"><small>SHIFT PAY</small><b>₦500</b></div></div><div className="progress"><div style={{width:`${state.energy}%`}}/></div><div className="shift-controls"><div><b>{state.energy}</b> energy remaining</div><button className="primary big" onClick={tap}><Zap/> WORK A SHIFT <span>+₦5</span></button></div></div><div className="panel jobs"><div className="panel-head"><h2>Career ladder</h2><span className="pill">More jobs unlock with wealth</span></div>{[['Freelancer','₦5 / tap','Starter'],['Shop Owner','₦25 / tap','₦10k capital'],['Property Manager','₦100 / tap','₦250k capital'],['CEO','₦500 / tap','₦5m capital']].map((x,i)=><div className="career" key={x[0]}><div className="career-no">0{i+1}</div><div><b>{x[0]}</b><span>{x[2]}</span></div><strong>{x[1]}</strong><span className={i===0?'unlocked':'locked'}>{i===0?'UNLOCKED':'LOCKED'}</span></div>)}</div></section>}
function MarketView({assets,buy,balance}){const [qty,setQty]=useState(1);return <section><div className="page-title row"><div><span className="eyebrow"><i/> LIVE MARKET</span><h1>Trade the real world.</h1><p>Prices in this simulation move continuously. Your cash stays virtual.</p></div><div className="balance-chip"><Wallet size={16}/> {money(balance)}</div></div><div className="market-grid">{assets.map(a=><div className="market-card panel" key={a.id}><div className="market-top"><div className="asset-icon big">{a.icon}</div><div><b>{a.name}</b><span>{a.ticker} · {a.type}</span></div><Activity size={16}/></div><div className="price">{money(a.price)}</div><div className={a.change>=0?'change up':'change down'}>{a.change>=0?<ArrowUpRight/>:<ArrowDownRight/>}{a.change.toFixed(2)}%</div><div className="spark"><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="trade-row"><input type="number" min="1" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))}/><button className="primary" onClick={()=>buy(a,qty)}>BUY</button></div></div>)}</div></section>}
function AssetsView({state,assets,portfolioValue}){const rows=Object.entries(state.portfolio).map(([id,q])=>{const a=assets.find(x=>x.id===id);return a?{...a,q}:null}).filter(Boolean);return <section><div className="page-title"><span className="eyebrow"><i/> OWNERSHIP</span><h1>Your portfolio.</h1><p>Everything you've earned and acquired lives here.</p></div><div className="metrics"><Metric icon={<Wallet/>} label="Portfolio Value" value={money(portfolioValue)}/><Metric icon={<Banknote/>} label="Available Cash" value={money(state.balance)}/><Metric icon={<LineChart/>} label="Positions" value={rows.length}/><Metric icon={<TrendingUp/>} label="Net Worth" value={money(state.balance+portfolioValue)}/></div><div className="panel"><div className="panel-head"><h2>Market holdings</h2></div>{rows.length?rows.map(a=><div className="holding" key={a.id}><div className="asset-icon">{a.icon}</div><div><b>{a.name}</b><span>{a.q} units · {a.ticker}</span></div><strong>{money(a.price*a.q)}</strong><span className="up">LIVE</span></div>):<div className="empty"><Wallet size={34}/><h3>No assets yet</h3><p>Work for your first capital, then enter the market.</p></div>}</div></section>}
function WorldView({state,properties,notify}){return <section><div className="page-title"><span className="eyebrow"><i/> VIRTUAL EARTH</span><h1>Own a piece of the world.</h1><p>Acquire virtual representations of real-world places and build your property empire.</p></div><div className="world-banner panel"><div><span className="kicker">EARTH MAP · SIMULATION</span><h2>Every city is an opportunity.</h2><p>Start with land. Graduate to homes, commercial property and entire districts.</p></div><div className="earth"><div className="continent c1"/><div className="continent c2"/><div className="continent c3"/></div></div><div className="property-grid">{properties.map(p=><div className="property panel" key={p.id}><div className="property-image"><div className="scene-glow"/><div className="scene-icon">{p.icon}</div><span>VIRTUAL PROPERTY</span></div><div className="property-body"><span className="location">{p.location}</span><h3>{p.name}</h3><div className="property-meta"><b>{money(p.price)}</b><span>{p.yield}% yield</span></div><button className="primary" onClick={()=>notify(state.balance>=p.price?'Property acquisition queued for settlement.':'Keep working: insufficient virtual cash.')}>ACQUIRE <ChevronRight size={15}/></button></div></div>)}</div></section>}
function CalculatorModal({close}){const [a,setA]=useState('1000000'),[r,setR]=useState('10'),[y,setY]=useState('5');const future=Number(a)*Math.pow(1+Number(r)/100,Number(y));return <div className="modal-back"><div className="calculator panel"><button className="close-modal" onClick={close}><X/></button><span className="eyebrow"><i/> WEALTH CALCULATOR</span><h2>Compound your future.</h2><p>Model returns inside the virtual economy.</p><label>Starting capital<input type="number" value={a} onChange={e=>setA(e.target.value)}/></label><label>Annual return %<input type="number" value={r} onChange={e=>setR(e.target.value)}/></label><label>Years<input type="number" value={y} onChange={e=>setY(e.target.value)}/></label><div className="calc-result"><span>Projected value</span><b>{money(future)}</b><small>Gain: {money(future-Number(a))}</small></div></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
